using UnityEngine;

public enum Events
{
    PICKUP_COLLECTED,
    ENEMY_KILLED,
    ENEMY_SPAWNED,
    ROOM_FINISHED,
    
    ALL_ENEMIES_DEAD,
    NORMAL_WAVE_DONE,
    NORMAL_WAVE_START,

    SPAWN_WAVE,
    ALL_WAVES_DONE,
    MOLD_CORE_SPAWNED,
    MOLD_CORE_KILLED,
    NEXT_SPAWNER,
    ALL_NEXT_SPAWNERS_DONE
}
