using UnityEngine;

public enum Events
{
    PICKUP_COLLECTED,
    ROOM_FINISHED,
    
    ENEMY_KILLED,
    ENEMY_SPAWNED,
    
    // WAVES RELATED EVENTS
    ALL_ENEMIES_DEAD,
    NORMAL_WAVE_DONE,
    NORMAL_WAVE_START,
    SPAWN_WAVE,
    ALL_WAVES_DONE,
    MOLD_CORE_SPAWNED,
    MOLD_CORE_KILLED,
    NEXT_SPAWNER,
    ALL_NEXT_SPAWNERS_DONE,

    // STATS RELATED EVENTS
    CRUMBS_CHANGED,
    HEALTH_CHANGED,
    STATISTIC_CHANGED ,

    // player attacks
    PLAYER_ATTACK_STARTED,
    PLAYER_ATTACK_ENDED

}
